apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl*
      - ./infra/k8s/orders-depl*
      - ./infra/k8s/payments-depl*
      - ./infra/k8s/tickets-depl*
      - ./infra/k8s/ingress*
      - ./infra/k8s/nats*
      - ./infra/k8s/shared-mongo*
build:
  googleCloudBuild:
    projectId: ticketing-dev-427705
  artifacts:
    - image: us.gcr.io/ticketing-dev-427705/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/ticketing-dev-427705/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.js'
    #         dest: .
    - image: us.gcr.io/ticketing-dev-427705/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-427705/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/ticketing-dev-427705/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: us.gcr.io/ticketing-dev-427705/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
